export enum ErrorCode {
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_CONFLICT = 'ORDER_CONFLICT',
  IDEMPOTENCY_KEY_CONFLICT = 'IDEMPOTENCY_KEY_CONFLICT',
  VERSION_MISMATCH = 'VERSION_MISMATCH',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  BAD_REQUEST = 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}


